name: publish lib to npmjs
on:
  push:
    branches: [develop]
    paths: [package.json]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    name: "publish npm"
    environment: pnpm
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install and Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
      - name: "Publish to the npm registry"
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.AUTOMATION }}
        with:
          default_branch: "develop"
